# Generated by Django 5.1.3 on 2024-12-04 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('strength_limit', models.CharField(max_length=10)),
                ('modulus_of_elasticity', models.CharField(max_length=10)),
                ('yield_strength', models.CharField(max_length=10)),
                ('elongation', models.CharField(max_length=5)),
                ('poisson_ratio', models.CharField(max_length=10)),
                ('ansys_file', models.FileField(upload_to='files')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['-publish'], name='db_list_mat_publish_35c1c1_idx')],
            },
        ),
    ]
