# Generated by Django 5.1.3 on 2024-12-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materials_stats',
            name='graph_file',
            field=models.FileField(default='settings.MEDIA_ROOT/files/sad_face.png', upload_to='graphs'),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_change', models.BooleanField(default=True, help_text='Is the member allowed to change the project data?', verbose_name='Allow Change')),
                ('allow_manage', models.BooleanField(default=False, help_text='Is the member allowed to manage users for the project?', verbose_name='Allow Manage')),
                ('project', models.ForeignKey(help_text='Project to which this user belongs', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='db_list.materials_stats', verbose_name='Project')),
                ('user', models.ForeignKey(help_text='User who belongs to this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
