# Generated by Django 5.1.3 on 2025-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_list', '0002_materials_stats_graph_file_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17)),
                ('confirmed_status', models.BooleanField()),
                ('administator_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='materials_stats',
            name='ludwig_const',
            field=models.FileField(default=0, max_length=6, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials_stats',
            name='material_hardening_index',
            field=models.FileField(default=0, max_length=10, upload_to=''),
            preserve_default=False,
        ),
    ]
