# Generated by Django 5.1.3 on 2025-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_list', '0003_author_materials_stats_ludwig_const_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials_stats',
            name='ludwig_const',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='materials_stats',
            name='material_hardening_index',
            field=models.CharField(max_length=10),
        ),
    ]
