# Generated by Django 5.1.5 on 2025-02-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_list", "0004_alter_materials_stats_ludwig_const_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.AddField(
            model_name="materials_stats",
            name="threeD_model",
            field=models.FileField(default=0, upload_to="3Dmodel"),
            preserve_default=False,
        ),
    ]
